### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by w4dd325** [Widen/axe-reporter-html#4]
Hi, I'm keen to use this but I don't understand how to trigger it. 

Can it be / is it, run from the command line as part of the axe run command?

**Comment by mskelton** [comment]
I build this as a utility used by [expect-axe-playwright](https://www.npmjs.com/package/expect-axe-playwright) and since I don't have a use case for it standalone with `axe.run` I did not build it to work that way.  I'd happily accept contributions though.
